language: node_js

node_js:
  - 0.10.33

before_script:
  - npm install
  - npm install forever -g
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - forever tests/support/server/index.js
  - sleep 3

script:
  - npm test
