language: node_js

node_js:
  - 0.10.33

before_script:
  - npm update -g npm
  - npm install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - node tests/support/server/index.js &
  - sleep 3

script:
  - npm test
